export const serviceOverviewData = {
  intro: [
    "If you are ever going to place your hands on a patient as a health care provider you will eventually be faced with a situation needing you to manage an airway; mostly involuntarily. The need to have a basic understanding of the airway is and should be part of every healthcare provider’s skill set. But airway skills come in handy for anyone. At Texas Airway Institute we start from the basics and give not only healthcare practitioners but even novices the opportunity to develop the necessary skills in airway management and advance these.",
    "This course offers the opportunity for anesthesiologists, residents, CRNAs, NPs, Medical Students, intensivists ,paramedics, surgeons, members of the Cardiac Arrest Team to improve their knowledge in this area.",
  ],

  achievements: [
    "Feel more comfortable in the management of basic and advanced airway",
    "Understand how to evaluate and easily identify a difficult Airway",
    "Know the difficult airway algorithm",
    "Anticipate and manage airway issues during induction and emergence of anesthesia as well as anywhere the need arises",
    "Know airway anatomy and what to look for during airway management",
    "Drugs needed for airway management and the choices.",
    "Non invasive airway management",
    "Surgical Airway",
    "Intubation Tips",
    "Use of vortex approach for unanticipated difficult Airway",
    "Communication tips during difficult situations",
  ],

  emergency: {
    title: "Airway Course Emergency: For Emergency Care providers.",
    description:
      "We offer a systematic approach to airway evaluation and management focusing on the challenges of being on the frontline with time sensitive events",
    left: [
      "Mastery of basics including tools for maintaining ventilation and upper airway anatomy",
      "The physiologically difficult Airway",
      "Forced to Act scenarios",
      "Cricothyrotomy and Needle thoracostomy",
      "RSI and choice of drugs",
      "EGA and SGA",
      "The Trauma Airway",
      "Airway in the obese patient",
      "Foreign body in Airway",
      "Decision making and strategy",
    ],
    right: [
      "Difficult Airway Algorithm",
      "The Anatomically difficult Airway",
      "SALAD",
      "The crash Airway",
      "The failed Airway",
      "DL, VL and tips for use under stress",
      "The pediatric airway",
      "Awake and FO intubation",
      "Non invasive ventilation options",
      "Code Stations and many more",
    ],
  },

  basics: {
    title: "Airway course The Basics:",
    left: [
      "For anyone who just wants to have the skills in management of basic airway like the nurse, the teacher, the bus driver, the day care personnel.",
      "One on one, fun skills course at your pace by experienced providers",
      "Well tailored modules for use at your pace.",
      "Additional skills to your BLS and Code Heart courses",
      "New and easy to use mannequins",
      "Courses provided year round for groups or individuals.",
    ],
    rightTitle: "What we offer:",
    right: [
      "How to start an IV.",
      "Upper Airway Anatomy.",
      "Principles of mask ventilation.",
      "Manual maneuvers for keeping the airway open and how to achieve the sniffing position.",
      "Airway adjuncts.",
      "Monitors during Airway management.",
      "The capnography use and interpretation .",
      "Signs and symptoms of a compromised Airway and management.",
      "And many more based on individual needs.",
    ],
  },

  anesthesia: {
    title: "Airway Course Anesthesiology and Critical Care.",
    description:
      "Above all get the peace of mind you need to manage any airway anytime, anywhere. We will focus on your specific areas of need and interest.",
    left: [
      "Fundamentals of Airway management include mask ventilation, sniffing position, and airway adjuncts.",
      "Use and Interpretation of standard ASA monitors during airway management and how reliable they are",
      "Supraglottic and Extraglottic devices",
      "Management of the anticipated and unanticipated Difficult Airway",
      "Difficult Airway Algorithms made easy",
      "Dealing with the obese patient",
      "Management of Airway complications like laryngospasm and vomit in Airway",
      "The physiologically difficult Airway and implications",
      "Airway management in Trauma",
      "The surgical Airway: Cricothyrotomy",
      "Crisis leadership and communication",
    ],
    right: [
      "Quick but effective evaluation of the airway",
      "Upper airway anatomy",
      "DL and VL and tips for successful intubation.",
      "Review of the latest ASA guidelines,",
      "The difficult extubation",
      "The airway in pregnancy",
      "Airway obstruction, evaluation, and management",
      "Fiber optic intubation",
      "Code Airway scenarios",
      "The Vortex approach to airway evaluation and management",
      "And much more.",
    ],
  },
};
