"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import {
  Download,
  Loader2,
  Printer,
  X,
  Image as ImageIcon,
  Mountain,
} from "lucide-react";
import { service_URL } from "@/config/env";
import { serviceClient } from "@/service/base/axios_client";
import { createAdminOrderLabel } from "@/service/admin/orders/order-label.service";
import type {
  AdminOrderLabelFormat,
  AdminOrderLabelOrientation,
} from "@/types/admin/orders/order-label.types";

type PrintOrderSlipModalProps = {
  open: boolean;
  orderId: string;
  onClose: () => void;
};

type SubmitState = "idle" | "loading" | "success";

function cx(...parts: Array<string | false | null | undefined>) {
  return parts.filter(Boolean).join(" ");
}

function buildAbsoluteUrl(url: string): string {
  if (!url) return "";
  if (url.startsWith("http://") || url.startsWith("https://")) {
    return url;
  }

  const normalizedBase = service_URL?.endsWith("/")
    ? service_URL.slice(0, -1)
    : service_URL;

  const normalizedPath = url.startsWith("/") ? url : `/${url}`;

  return `${normalizedBase}${normalizedPath}`;
}

export default function PrintOrderSlipModal({
  open,
  orderId,
  onClose,
}: PrintOrderSlipModalProps) {
  const [labelFormat, setLabelFormat] = useState<AdminOrderLabelFormat>("4x6");
  const [orientation, setOrientation] =
    useState<AdminOrderLabelOrientation>("portrait");
  const [includePackingSlip, setIncludePackingSlip] = useState(true);
  const [printInstructions, setPrintInstructions] = useState(false);

  const [submitState, setSubmitState] = useState<SubmitState>("idle");
  const [message, setMessage] = useState("");
  const [previewUrl, setPreviewUrl] = useState("");
  const [downloadUrl, setDownloadUrl] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [previewBlobUrl, setPreviewBlobUrl] = useState("");
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);

  const hasAutoGeneratedRef = useRef(false);
  const latestPreviewBlobUrlRef = useRef("");

  useEffect(() => {
    latestPreviewBlobUrlRef.current = previewBlobUrl;
  }, [previewBlobUrl]);

  const clearPreviewBlobUrl = useCallback(() => {
    const currentBlobUrl = latestPreviewBlobUrlRef.current;

    if (currentBlobUrl) {
      URL.revokeObjectURL(currentBlobUrl);
      latestPreviewBlobUrlRef.current = "";
    }

    setPreviewBlobUrl("");
  }, []);

  const resetState = useCallback(() => {
    clearPreviewBlobUrl();
    setPreviewUrl("");
    setDownloadUrl("");
    setMessage("");
    setErrorMessage("");
    setSubmitState("idle");
    setIsPreviewLoading(false);
    hasAutoGeneratedRef.current = false;
  }, [clearPreviewBlobUrl]);

  useEffect(() => {
    if (!open) return;

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    return () => {
      document.body.style.overflow = previousOverflow;
    };
  }, [open]);

  useEffect(() => {
    if (!open) return;

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape" && submitState !== "loading") {
        onClose();
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [open, onClose, submitState]);

  useEffect(() => {
    if (!open) {
      resetState();
    }
  }, [open, resetState]);

  useEffect(() => {
    return () => {
      const currentBlobUrl = latestPreviewBlobUrlRef.current;
      if (currentBlobUrl) {
        URL.revokeObjectURL(currentBlobUrl);
      }
    };
  }, []);

  const canClose = submitState !== "loading" && !isPreviewLoading;

  const resolvedPreviewUrl = useMemo(
    () => buildAbsoluteUrl(previewUrl),
    [previewUrl],
  );

  const resolvedDownloadUrl = useMemo(
    () => buildAbsoluteUrl(downloadUrl),
    [downloadUrl],
  );

  const fetchFileBlobUrl = useCallback(async (url: string): Promise<string> => {
    const absoluteUrl = buildAbsoluteUrl(url);

    const response = await serviceClient.get<Blob>(absoluteUrl, {
      responseType: "blob",
    });

    return URL.createObjectURL(response.data);
  }, []);

  const generateLabel = useCallback(async () => {
    try {
      setSubmitState("loading");
      setIsPreviewLoading(true);
      setErrorMessage("");
      setMessage("");
      clearPreviewBlobUrl();

      const response = await createAdminOrderLabel(orderId, {
        labelFormat,
        orientation,
        includePackingSlip,
        printInstructions,
      });

      const nextPreviewUrl = response.label?.previewUrl || "";
      const nextDownloadUrl = response.label?.downloadUrl || "";

      setMessage(response.message || "Shipping label generated successfully.");
      setPreviewUrl(nextPreviewUrl);
      setDownloadUrl(nextDownloadUrl);
      setSubmitState("success");

      if (!nextPreviewUrl) {
        setIsPreviewLoading(false);
        setErrorMessage("Preview unavailable.");
        return;
      }

      const blobUrl = await fetchFileBlobUrl(nextPreviewUrl);
      setPreviewBlobUrl(blobUrl);
    } catch (error) {
      console.error("Failed to generate shipping label:", error);
      setSubmitState("idle");
      setErrorMessage("Failed to generate shipping label. Please try again.");
    } finally {
      setIsPreviewLoading(false);
    }
  }, [
    clearPreviewBlobUrl,
    fetchFileBlobUrl,
    includePackingSlip,
    labelFormat,
    orderId,
    orientation,
    printInstructions,
  ]);

  useEffect(() => {
    if (!open || hasAutoGeneratedRef.current) return;

    hasAutoGeneratedRef.current = true;
    void generateLabel();
  }, [generateLabel, open]);

  const handleDownload = async () => {
    if (!resolvedDownloadUrl) return;

    try {
      const response = await serviceClient.get<Blob>(resolvedDownloadUrl, {
        responseType: "blob",
      });

      const blobUrl = URL.createObjectURL(response.data);
      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = `shipping-label-${orderId}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(blobUrl);
    } catch (error) {
      console.error("Failed to download shipping label:", error);
      setErrorMessage("Failed to download shipping label. Please try again.");
    }
  };

  const handlePrint = () => {
    if (!previewBlobUrl) return;

    const printWindow = window.open(
      previewBlobUrl,
      "_blank",
      "noopener,noreferrer",
    );

    if (!printWindow) return;

    printWindow.focus();
  };

  const handleRegenerate = () => {
    void generateLabel();
  };

  if (!open) return null;

  return createPortal(
    <div className="fixed inset-0 z-[9999]">
      <button
        type="button"
        aria-label="Close modal"
        disabled={!canClose}
        onClick={onClose}
        className="absolute inset-0 bg-slate-900/30 backdrop-blur-[2px]"
      />

      <div className="relative flex h-full w-full items-center justify-center p-4">
        <div className="flex max-h-[92vh] w-full max-w-5xl flex-col overflow-hidden rounded-[28px] bg-white shadow-2xl">
          <div className="flex items-start justify-between border-b border-slate-200 px-7 py-5">
            <div>
              <h2 className="text-sm font-bold text-slate-900 sm:text-base">
                Print Shipping Label
              </h2>
              <p className="mt-1 text-xs font-medium text-slate-500">
                Order ID #{orderId}
              </p>
            </div>

            <button
              type="button"
              disabled={!canClose}
              onClick={onClose}
              className="rounded-full p-2 text-slate-400 transition hover:bg-slate-100 hover:text-slate-600 disabled:opacity-50"
            >
              <X size={18} />
            </button>
          </div>

          <div className="grid min-h-0 flex-1 grid-cols-1 overflow-y-auto lg:grid-cols-[1.15fr_0.85fr]">
            <div className="bg-[#f8fafc] px-5 py-5 sm:px-7 sm:py-6">
              <div className="mx-auto flex h-full min-h-[420px] w-full max-w-[430px] items-center justify-center rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm">
                {isPreviewLoading ? (
                  <div className="flex h-[560px] w-full flex-col items-center justify-center rounded-2xl border border-slate-200 bg-white">
                    <Loader2 className="h-8 w-8 animate-spin text-slate-400" />
                    <p className="mt-3 text-sm font-medium text-slate-500">
                      Loading label preview...
                    </p>
                  </div>
                ) : previewBlobUrl ? (
                  <iframe
                    title="Shipping label preview"
                    src={previewBlobUrl}
                    className="h-[560px] w-full rounded-2xl border border-slate-200 bg-white"
                  />
                ) : (
                  <div className="flex h-[560px] w-full items-center justify-center rounded-2xl border border-slate-200 bg-white text-sm font-medium text-slate-500">
                    Preview unavailable
                  </div>
                )}
              </div>
            </div>

            <div className="flex flex-col bg-white px-5 py-5 sm:px-7 sm:py-6  justify-between">
              <div className="space-y-6">
                <div>
                  <div className="text-xs font-bold uppercase tracking-wide text-slate-700">
                    Label Format
                  </div>

                  <div className="mt-3">
                    <button
                      type="button"
                      className="flex w-full items-center justify-between rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700"
                    >
                      <span>4×6 Thermal Label</span>
                    </button>
                  </div>
                </div>

                {/* <div>
                  <div className="text-xs font-bold uppercase tracking-wide text-slate-700">
                    Orientation
                  </div>

                  <div className="mt-3 grid grid-cols-2 gap-3">
                    <button
                      type="button"
                      onClick={() => setOrientation("portrait")}
                      className={cx(
                        "flex items-center justify-center gap-2 rounded-2xl border px-4 py-3 text-sm font-semibold transition",
                        orientation === "portrait"
                          ? "border-cyan-400 bg-cyan-50 text-cyan-700"
                          : "border-slate-200 bg-white text-slate-500 hover:bg-slate-50",
                      )}
                    >
                      <ImageIcon size={16} />
                      Portrait
                    </button>

                    <button
                      type="button"
                      onClick={() => setOrientation("landscape")}
                      className={cx(
                        "flex items-center justify-center gap-2 rounded-2xl border px-4 py-3 text-sm font-semibold transition",
                        orientation === "landscape"
                          ? "border-cyan-400 bg-cyan-50 text-cyan-700"
                          : "border-slate-200 bg-white text-slate-500 hover:bg-slate-50",
                      )}
                    >
                      <Mountain size={16} />
                      Landscape
                    </button>
                  </div>
                </div> */}

                {/* <div className="space-y-4 border-t border-slate-100 pt-6">
                  <ToggleRow
                    title="Include Packing Slip"
                    description="Attach detailed list of clinical gear"
                    checked={includePackingSlip}
                    onChange={setIncludePackingSlip}
                  />

                  <ToggleRow
                    title="Print Instructions"
                    description="Add clinical handling guide"
                    checked={printInstructions}
                    onChange={setPrintInstructions}
                  />
                </div> */}

                <div className="rounded-2xl bg-slate-50 px-4 py-4 text-xs font-medium text-slate-500">
                  Shipping via{" "}
                  <span className="font-bold text-slate-700">
                    FedEx Priority Overnight
                  </span>
                  . Expected delivery by
                  <span className="font-bold text-slate-700">
                    {" "}
                    10:30 AM tomorrow.
                  </span>
                </div>

                {errorMessage ? (
                  <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-xs font-semibold text-red-600">
                    {errorMessage}
                  </div>
                ) : null}

                {submitState === "success" && message ? (
                  <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-700">
                    {message}
                  </div>
                ) : null}
              </div>

              <div className="mt-8 flex flex-col gap-3 border-t border-slate-200 pt-5 sm:flex-row justify-end">
                {/* <button
                  type="button"
                  onClick={handleRegenerate}
                  disabled={submitState === "loading" || isPreviewLoading}
                  className="inline-flex items-center justify-center rounded-2xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  Regenerate Label
                </button> */}

                <button
                  type="button"
                  onClick={handleDownload}
                  disabled={!resolvedDownloadUrl || isPreviewLoading}
                  className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  <Download size={16} />
                  Download PDF
                </button>

                <button
                  type="button"
                  onClick={handlePrint}
                  disabled={!previewBlobUrl || isPreviewLoading}
                  className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[var(--primary)] px-5 py-3 text-sm font-bold text-white hover:bg-[var(--primary-hover)] disabled:cursor-not-allowed disabled:opacity-60"
                >
                  <Printer size={16} />
                  Print Label
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>,
    document.body,
  );
}

function ToggleRow({
  title,
  description,
  checked,
  onChange,
}: {
  title: string;
  description: string;
  checked: boolean;
  onChange: (value: boolean) => void;
}) {
  return (
    <div className="flex items-center justify-between gap-4">
      <div className="min-w-0">
        <div className="text-sm font-bold text-slate-800">{title}</div>
        <div className="mt-1 text-xs font-medium text-slate-500">
          {description}
        </div>
      </div>

      <button
        type="button"
        onClick={() => onChange(!checked)}
        className={cx(
          "relative h-7 w-12 rounded-full transition",
          checked ? "bg-[var(--primary)]" : "bg-slate-200",
        )}
      >
        <span
          className={cx(
            "absolute top-1 h-5 w-5 rounded-full bg-white shadow-sm transition",
            checked ? "left-6" : "left-1",
          )}
        />
      </button>
    </div>
  );
}
