import type { CourseAnnouncementsData } from "../types/course-annoucements-types";

export const COURSE_ANNOUNCEMENTS_MOCK: CourseAnnouncementsData = {
  metrics: {
    totalActiveStudents: 288,
    activeStudentsDeltaLabel: "+15 / week",
    scheduledBroadcasts: 4,
    scheduledBroadcastsSubLabel: "Pending",
    averageCohortSize: 24,
    averageCohortSizeUnitLabel: "Students",
  },
  cohorts: [
    {
      id: "c1",
      title: "Advanced Airway Management",
      dateLabel: "Mar 12, 2026",
      status: "upcoming",
      rightBadge: { label: "Open", tone: "success" },
      metric: { key: "enrolled", value: 32, label: "STUDENTS ENROLLED" },
      tags: [{ id: "t1", label: "Workshop" }],
      cta: { label: "Compose Announcement", tone: "primary" },
    },
    {
      id: "c2",
      title: "Point-of-Care Ultrasound",
      dateLabel: "Apr 06, 2026",
      status: "upcoming",
      rightBadge: { label: "Open", tone: "success" },
      metric: { key: "enrolled", value: 18, label: "STUDENTS ENROLLED" },
      tags: [{ id: "t1", label: "Workshop" }],
      cta: { label: "Compose Announcement", tone: "primary" },
    },
    {
      id: "c3",
      title: "Pediatric Respiratory Crisis",
      dateLabel: "Jan 15, 2026",
      status: "completed",
      rightBadge: { label: "Completed", tone: "neutral" },
      metric: { key: "completed", value: 24, label: "STUDENTS COMPLETED" },
      tags: [{ id: "t2", label: "Completed" }],
      cta: { label: "Compose Announcement", tone: "indigo" },
    },
    {
      id: "c4",
      title: "Cardiac Echo Foundations",
      dateLabel: "Feb 18, 2026",
      status: "cancelled",
      rightBadge: { label: "Cancelled", tone: "neutral" },
      metric: { key: "impacted", value: 14, label: "STUDENTS IMPACTED" },
      tags: [{ id: "t3", label: "Cancelled" }],
      cta: { label: "Compose Announcement", tone: "danger" },
    },
    {
      id: "c5",
      title: "Fiberoptic Intubation Masterclass",
      dateLabel: "Jul 02, 2026",
      status: "upcoming",
      rightBadge: { label: "Open", tone: "success" },
      metric: { key: "enrolled", value: 12, label: "STUDENTS ENROLLED" },
      tags: [{ id: "t1", label: "Workshop" }],
      cta: { label: "Compose Announcement", tone: "primary" },
    },
  ],
};