import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "react-day-picker/dist/style.css";
import "./globals.css";
import { CartProvider } from "@/app/public/context/cart-context";
import { WishlistProvider } from "@/app/public/context/wishlist-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-slate-50">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-slate-50 antialiased`}
      >
        <CartProvider>
          <WishlistProvider>
            {children}
            <Toaster
              position="top-center"
              toastOptions={{
                duration: 3000,
              }}
            />
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
